import type { Indicator, WeightPreset } from "./types"

export const YEARS = [2019, 2020, 2021, 2022, 2023, 2024]

export const INDICATORS: Indicator[] = [
  {
    id: "gini",
    name: "Gini Ratio",
    unit: "index",
    direction: "higher_is_worse",
    defaultNormalization: "raw",
  },
  {
    id: "p0",
    name: "Persentase Penduduk Miskin",
    unit: "%",
    direction: "higher_is_worse",
    defaultNormalization: "raw",
  },
  {
    id: "jumlah_miskin",
    name: "Jumlah Penduduk Miskin",
    unit: "jiwa",
    direction: "higher_is_worse",
    defaultNormalization: "per_100k",
  },
  {
    id: "tpt",
    name: "Tingkat Pengangguran Terbuka",
    unit: "%",
    direction: "higher_is_worse",
    defaultNormalization: "raw",
  },
  {
    id: "angkatan_kerja",
    name: "Jumlah Angkatan Kerja",
    unit: "jiwa",
    direction: "higher_is_better",
    defaultNormalization: "per_100k",
  },
  {
    id: "penduduk_bekerja",
    name: "Jumlah Penduduk Bekerja",
    unit: "jiwa",
    direction: "higher_is_better",
    defaultNormalization: "per_100k",
  },
  {
    id: "rata_upah",
    name: "Rata-rata Upah/Gaji Bulanan",
    unit: "Rp",
    direction: "higher_is_better",
    defaultNormalization: "raw",
  },
  {
    id: "ump",
    name: "Upah Minimum Provinsi",
    unit: "Rp",
    direction: "higher_is_better",
    defaultNormalization: "raw",
  },
  {
    id: "ihk",
    name: "Indeks Harga Konsumen",
    unit: "index",
    direction: "higher_is_worse",
    defaultNormalization: "raw",
  },
  {
    id: "ipm",
    name: "Indeks Pembangunan Manusia",
    unit: "index",
    direction: "higher_is_better",
    defaultNormalization: "raw",
  },
  {
    id: "pdrb_kapita",
    name: "PDRB per Kapita",
    unit: "Rp",
    direction: "higher_is_better",
    defaultNormalization: "raw",
  },
]

export const PRESETS: WeightPreset[] = [
  {
    id: "balanced",
    name: "Balanced",
    weights: {
      gini: 15,
      p0: 15,
      jumlah_miskin: 10,
      tpt: 10,
      angkatan_kerja: 5,
      penduduk_bekerja: 5,
      rata_upah: 10,
      ump: 5,
      ihk: 5,
      ipm: 10,
      pdrb_kapita: 10,
    },
  },
  {
    id: "poverty",
    name: "Poverty-focused",
    weights: {
      gini: 20,
      p0: 30,
      jumlah_miskin: 20,
      tpt: 10,
      angkatan_kerja: 0,
      penduduk_bekerja: 0,
      rata_upah: 5,
      ump: 5,
      ihk: 0,
      ipm: 5,
      pdrb_kapita: 5,
    },
  },
]

export const PROVINCES = [
  { id: "11", name: "Aceh" },
  { id: "12", name: "Sumatera Utara" },
  { id: "13", name: "Sumatera Barat" },
  { id: "14", name: "Riau" },
  { id: "15", name: "Jambi" },
  { id: "16", name: "Sumatera Selatan" },
  { id: "17", name: "Bengkulu" },
  { id: "18", name: "Lampung" },
  { id: "19", name: "Kep. Bangka Belitung" },
  { id: "21", name: "Kep. Riau" },
  { id: "31", name: "DKI Jakarta" },
  { id: "32", name: "Jawa Barat" },
  { id: "33", name: "Jawa Tengah" },
  { id: "34", name: "DI Yogyakarta" },
  { id: "35", name: "Jawa Timur" },
  { id: "36", name: "Banten" },
  { id: "51", name: "Bali" },
  { id: "52", name: "Nusa Tenggara Barat" },
  { id: "53", name: "Nusa Tenggara Timur" },
  { id: "61", name: "Kalimantan Barat" },
  { id: "62", name: "Kalimantan Tengah" },
  { id: "63", name: "Kalimantan Selatan" },
  { id: "64", name: "Kalimantan Timur" },
  { id: "65", name: "Kalimantan Utara" },
  { id: "71", name: "Sulawesi Utara" },
  { id: "72", name: "Sulawesi Tengah" },
  { id: "73", name: "Sulawesi Selatan" },
  { id: "74", name: "Sulawesi Tenggara" },
  { id: "75", name: "Gorontalo" },
  { id: "76", name: "Sulawesi Barat" },
  { id: "81", name: "Maluku" },
  { id: "82", name: "Maluku Utara" },
  { id: "91", name: "Papua Barat" },
  { id: "92", name: "Papua Barat Daya" },
  { id: "94", name: "Papua" },
  { id: "95", name: "Papua Selatan" },
  { id: "96", name: "Papua Tengah" },
  { id: "97", name: "Papua Pegunungan" },
]
